apiVersion: v1
kind: Service
metadata:
  labels:
    app: solar-system
  name: solar-system
  namespace: ${NAMESPACE}
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: solar-system 
  type: LoadBalancer
