apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    spec.ingressClassName: nginx
#    cert-manager.io/issuer: letsencrypt-prod
  name: solar-system
  namespace: ${NAMESPACE}
spec:
    rules:
    - host: solar-system-${NAMESPACE}.${INGRESS_IP}.nip.io
      http:
        paths:
        - backend:
            service:
              name: solar-system
              port:
                number: 3000
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - solar-system-${NAMESPACE}.${INGRESS_IP}.nip.io